version: "3.8"

services:
  postgres:
    image: postgres:16.2
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: $POSTGRES_USER

  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
