FROM python:3.12-slim

WORKDIR /tests

COPY requirements-test.txt /tests

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN pip install pip --upgrade &&  pip install -r requirements-test.txt

COPY . /tests

ENV PYTHONPATH=.
CMD [ "pytest", "--cov=.", "tests.py" ]
