version: "3.8"

services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: $POSTGRES_USER

  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      postgres:
        condition: service_healthy
